name: Sync gh-pages with main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Push to gh-pages
        run: |
          git checkout gh-pages
          git rebase main
          git push origin gh-pages
